language: bash

services:
  - docker

script:
  - cd ${TRAVIS_BUILD_DIR}/photofeed && bash build-docker.sh
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push zjor/photofeed:latest

