language: bash

services:
  - docker

script:
  - bash photofeed/build-docker.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zjor/photofeed:latest

