version: '3'

services:

  photofeed-db:
    image: postgres:10.6-alpine
    volumes:
    - /tmp/var/lib/photofeed/postgresql/data:/var/lib/postgresql/data
    ports:
    - "6432:5432"
    environment:
      POSTGRES_DB: photofeed
      POSTGRES_USER: photofeed
      POSTGRES_PASSWORD: s3cr3t

  web:
    build: ./photofeed/
    # image: zjor/photofeed:latest
    command: bash -c "./wait-for-postgres.sh photofeed-db python manage.py makemigrations && python manage.py migrate && python manage.py loaddata init && python manage.py runserver 0.0.0.0:8000"
    container_name: photofeed
    ports:
      - "9000:8000"
    environment:
      DB_USER: photofeed
      DB_PASS: s3cr3t      