kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: photofeed
  name: photofeed-db
  labels:
    type: local  
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/photofeed/volume-db"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: photofeed  
  name: photofeed-db  
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
