# Generated by Django 2.2.1 on 2019-06-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('creation_date', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-creation_date', 'id'],
            },
        ),
    ]
